### ISSUE TITLE
Gromacs Benchmark Input Data Missing

### ISSUE THREAD

**Issue by drwhitehouse** [hpc-uk/archer-benchmarks#16]
Hi, we would like to make use of your input data for the Gromacs benchmarks (https://github.com/hpc-uk/archer-benchmarks/tree/master/apps/GROMACS) however it appears that the links to the external file sharing sites are no longer working.

**Comment by aturner-epcc** [comment]
@drwhitehouse Apologies, the raw input files are now up and accessible again. The binary input will follow next week. See the new link at:

https://github.com/hpc-uk/archer-benchmarks/tree/master/apps/GROMACS

**Comment by drwhitehouse** [comment]
Thanks very much indeed!

**Comment by aturner-epcc** [comment]
@drwhitehouse Binary data now up too so I am closing this issue.
